version: '3.9'

services:
  app:
    build: .
    container_name: geotrix-app
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:7
    container_name: geotrix-mongo

    command:
      - --replSet
      - rs0
      - --bind_ip_all

    ports:
      - '27018:27017'

    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: geotrix-redis
    ports:
      - '6379:6379'

volumes:
  mongo_data: